spring.application.name=clean_civic_app

spring.datasource.url=jdbc:mysql://localhost:3306/clean_civic
spring.datasource.username=root
spring.datasource.password=Aditya

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

app.jwt.secret=CleanCivicSuperSecretKey2026ChangeThisBeforeProduction123
app.jwt.expiration=86400000
cloudinary.cloud-name=cbt5wdqj
cloudinary.api-key=537452567318512
cloudinary.api-secret=TOVzj6N6aTgUJAWkI6QZVONpqLs